- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: example using security group rule descriptions
    amazon.aws.ec2_group:
      name: samplesg
      description: sg with rule descriptions
      vpc_id: vpc-5adb7031
     #profile: "{{ aws_profile }}"
      region: "{{ my_region }}"
      aws_access_key: "{{ my_access_key }}"
      aws_secret_key: "{{ my_secret_key }}"
      rules:
        - proto: tcp
          ports:
          - 80
          cidr_ip: 0.0.0.0/16
          rule_desc: allow all on port 80
