- hosts: 127.0.0.1
  connection: local
  tasks:
  # Basic user creation example
  - name: Create two new IAM users with API keys
    iam:
      iam_type: user
      aws_access_key: "{{ my_access_key }}"
      aws_secret_key: "{{ my_secret_key }}"
      name: "{{ item }}"
      state: present
      password: "{{ temp_pass }}"
      access_key_state: create
    with_items:
      - admin
  
